
default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development
  encoding: utf8
  pool: 5
  username: root
  password: 123456
  socket: /tmp/mysql.sock

test:
  <<: *default
  database: db/test
  encoding: utf8
  pool: 5
  username: root
  password: 123456
  socket: /tmp/mysql.sock

production:
  <<: *default
  database: db/production
  encoding: utf8
  pool: 5
  username: root
  password: 123456
  socket: /tmp/mysql.sock
